// app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Menu/Header";
import MenuNgang from "@/components/Menu/Menu_ngang";
import InitAuth from "@/Initialize-once/InitAuth";
import ChatBoxManager from "@/components/Message/ChatBoxManager";
import InitConversation from "@/service/start/InitConversation";
// import 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/transparent-Photoroom.png" },
};


export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiase bg-white`}>
        {/* <InitAuth/> */}
         <Header />
          {children}
          <ChatBoxManager/>
          <InitConversation />
      </body>
    </html>
  );
}
